version: '3.8'

services:
  # Federated Learning Coordinator
  fl-coordinator:
    build:
      context: .
      dockerfile: Dockerfile.coordinator
    container_name: fl-coordinator
    ports:
      - "9000:8000"
    volumes:
      - ./api:/app/api
      - ./models:/app/models
      - ./cache:/app/cache
      - ./logs:/app/logs
      - ./database:/app/database
      - pip-cache:/root/.cache/pip
    environment:
      - PYTHONPATH=/app
      - TORCH_HOME=/app/cache/torch
      - NVIDIA_VISIBLE_DEVICES=all
      - MODEL_PATH=/app/models/best_pretrained_model.pth
      - DATABASE_URL=sqlite:////app/database/federated.db
      - JWT_SECRET=coordinator-secret-key
      - NODE_TYPE=coordinator
      - FEDERATED_ROUNDS=10
      - LOG_LEVEL=INFO
      - ENABLE_DP=true
      - MAX_DP_EPSILON=100.0
      - DP_DELTA=1e-5
      - DP_NOISE_MULTIPLIER=0.2
      - DP_MAX_GRAD_NORM=5.0
    command: uvicorn api.src.coordinator:app --host 0.0.0.0 --reload
    restart: unless-stopped
    networks:
      - biometric-net

  # Client 1 Biometric API Service
  client1-api:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: client1-biometric-api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/api
      - ./data:/app/data
      - ./models:/app/models
      - ./cache:/app/cache
      - ./logs:/app/logs
      - ./database/client1.db:/app/database/facial_reg.db
      - pip-cache:/root/.cache/pip
    environment:
      - PYTHONPATH=/app
      - TORCH_HOME=/app/cache/torch
      - NVIDIA_VISIBLE_DEVICES=all
      - MODEL_PATH=/app/models/best_client1_pretrained_model.pth
      - DATABASE_URL=sqlite:////app/database/facial_reg.db
      - JWT_SECRET=your-secret-key
      - RATE_LIMIT_AUTH=5
      - RATE_LIMIT_DEFAULT=10
      - MAX_WORKERS=1
      - LOG_LEVEL=INFO
      - ENABLE_DP=true
      - MAX_DP_EPSILON=100.0
      - DP_DELTA=1e-5
      - DP_NOISE_MULTIPLIER=0.2
      - DP_MAX_GRAD_NORM=5.0
      - CUDA_VISIBLE_DEVICES=0
      - TORCH_USE_CUDA_DSA=1
      - CUDA_LAUNCH_BLOCKING=1
      - RELOAD=true
      - NODE_TYPE=client
      - CLIENT_ID=client1
      - COORDINATOR_URL=http://fl-coordinator:8000
    command: uvicorn api.src.app:app --host 0.0.0.0 --reload
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    mem_limit: 4g
    restart: unless-stopped
    networks:
      - biometric-net
    depends_on:
      - fl-coordinator

  # Client 2 Biometric API Service
  client2-api:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: client2-biometric-api
    ports:
      - "8001:8000"
    volumes:
      - ./api:/app/api
      - ./data:/app/data
      - ./models:/app/models
      - ./cache:/app/cache
      - ./logs:/app/logs
      - ./database/client2.db:/app/database/facial_reg.db
      - pip-cache:/root/.cache/pip
    environment:
      - PYTHONPATH=/app
      - TORCH_HOME=/app/cache/torch
      - NVIDIA_VISIBLE_DEVICES=all
      - MODEL_PATH=/app/models/best_client2_pretrained_model.pth
      - DATABASE_URL=sqlite:////app/database/facial_reg.db
      - JWT_SECRET=your-secret-key-client2
      - RATE_LIMIT_AUTH=5
      - RATE_LIMIT_DEFAULT=10
      - MAX_WORKERS=1
      - LOG_LEVEL=INFO
      - ENABLE_DP=true
      - MAX_DP_EPSILON=100.0
      - DP_DELTA=1e-5
      - DP_NOISE_MULTIPLIER=0.2
      - DP_MAX_GRAD_NORM=5.0
      - CUDA_VISIBLE_DEVICES=0
      - TORCH_USE_CUDA_DSA=1
      - CUDA_LAUNCH_BLOCKING=1
      - RELOAD=true
      - NODE_TYPE=client
      - CLIENT_ID=client2
      - COORDINATOR_URL=http://fl-coordinator:8000
    command: uvicorn api.src.app:app --host 0.0.0.0 --reload
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    mem_limit: 4g
    restart: unless-stopped
    networks:
      - biometric-net
    depends_on:
      - fl-coordinator

  # Emotion Analysis API Service
  emotion-api:
    build:
      context: ./emo-api
      dockerfile: Dockerfile
    container_name: emotion-api
    ports:
      - "1236:8080"
    volumes:
      - ./emo-api/model.pth:/app/model.pth
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - MODEL_PATH=/app/model.pth
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - biometric-net

networks:
  biometric-net:
    driver: bridge

volumes:
  biometric_cache:
    driver: local
  biometric_logs:
    driver: local
  pip-cache:
    name: facial-reg-pip-cache
  