global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'biometric-api'
    static_configs:
      - targets: ['biometric-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'federated-coordinator'
    static_configs:
      - targets: ['federated-coordinator:8001']
    metrics_path: '/health'
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
